@url_user = http://localhost:3000/api/user/

@url_category= http://localhost:3000/api/category/
@url_article= http://localhost:3000/api/article/

@json_user = Content-Type: application/json
@json_category = content-Type: application/json
@json_article = content-Type: application/json


###
#POST Register New User
POST {{url_user}}register
{{json_user}}

{
    "name": "Edward",
    "email": "stianyu99@vt.edu",
    "password": "123456",
    "identity": "Admin"
}

###
#GET List All User - Testing (No Need Authorization)
GET {{url_user}}users

###
#POST Login
POST {{url_user}}login
{{json_user}}

{
    "email": "stianyu99@vt.edu",
    "password": "123456"
}

# Current User Private API should be fixed later
###
#GET Current User Testing
GET {{url_user}}current
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MDYzYmZmNzczNjVkOGJmYzA4MTk5MyIsIm5hbWUiOiJFZHdhcmQiLCJpZGVudGl0eSI6IkFkbWluIiwiaWF0IjoxNjk0OTM0NDIxLCJleHAiOjE2OTQ5Mzc0MjF9.GtdE3_Ha9rAhjz64X4I-wCfzgiSu9YsDRXq0iPiLGxI

##############################################################################################

###--- Category
#Post Create a Category
POST {{url_category}}create
{{json_category}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MDYzYmZmNzczNjVkOGJmYzA4MTk5MyIsIm5hbWUiOiJFZHdhcmQiLCJpZGVudGl0eSI6IkFkbWluIiwiaWF0IjoxNjk0OTM0NDIxLCJleHAiOjE2OTQ5Mzc0MjF9.GtdE3_Ha9rAhjz64X4I-wCfzgiSu9YsDRXq0iPiLGxI

{
    "name":"JavaScript",
    "parent":"65069fac698e7a712e72dc9b"
}

###
#GET ALL Categorical List by User
GET {{url_category}}categoicalList
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MDYzYmZmNzczNjVkOGJmYzA4MTk5MyIsIm5hbWUiOiJFZHdhcmQiLCJpZGVudGl0eSI6IkFkbWluIiwiaWF0IjoxNjk0OTM0NDIxLCJleHAiOjE2OTQ5Mzc0MjF9.GtdE3_Ha9rAhjz64X4I-wCfzgiSu9YsDRXq0iPiLGxI

###
#PUT Update one of Categories
PUT {{url_category}}65069624d281709fa7340802
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MDYzYmZmNzczNjVkOGJmYzA4MTk5MyIsIm5hbWUiOiJFZHdhcmQiLCJpZGVudGl0eSI6IkFkbWluIiwiaWF0IjoxNjk0OTM0NDIxLCJleHAiOjE2OTQ5Mzc0MjF9.GtdE3_Ha9rAhjz64X4I-wCfzgiSu9YsDRXq0iPiLGxI
{{json_category}}

{
    "name": "Traveling"
}

###
#DELETE Delete one of Categories
DELETE {{url_category}}65069ade868c6f3b5909d670
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MDYzYmZmNzczNjVkOGJmYzA4MTk5MyIsIm5hbWUiOiJFZHdhcmQiLCJpZGVudGl0eSI6IkFkbWluIiwiaWF0IjoxNjk0OTM0NDIxLCJleHAiOjE2OTQ5Mzc0MjF9.GtdE3_Ha9rAhjz64X4I-wCfzgiSu9YsDRXq0iPiLGxI


###
#GET List All Categories - Testing (No Need Authorization)
GET {{url_category}}categories

##############################################################################################

###--- Article

###
#POST Create a Task
POST {{url_task}}create
{{json_task}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MGE2YjViMDQzOTFlZDdkN2Q4ZTAwOSIsIm5hbWUiOiJFZHdhcmQiLCJpZGVudGl0eSI6IkFkbWluIiwiaWF0IjoxNjc4NTIxMTA0LCJleHAiOjE2Nzg1MjQxMDR9.y7ElXaq343_ERcMSsbB_0t-esR1BJzg4KzM5KfrVkFw"

{
    "userId": "640a6b5b04391ed7d7d8e009",
    "taskName": "Project Proposal",
    "status": "Pending",
    "date": "2023/04/30"
}