@url_user = http://localhost:3000/api/user/
@url_category= http://localhost:3000/api/category/
@url_article= http://localhost:3000/api/article/

@json_user = Content-Type: application/json
@json_category = content-Type: application/json
@json_article = content-Type: application/json


###
#POST Register New User
POST {{url_user}}register
{{json_user}}

{
    "name": "Edward",
    "email": "stianyu99@vt.edu",
    "password": "123456",
    "identity": "Admin"
}

###
#POST Login
POST {{url_user}}login
{{json_user}}

{
    "email": "stianyu99@vt.edu",
    "password": "123456"
}

# Current User Private API
###
#GET Current User Testing
GET {{url_user}}current
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MDYzYmZmNzczNjVkOGJmYzA4MTk5MyIsIm5hbWUiOiJFZHdhcmQiLCJpZGVudGl0eSI6IkFkbWluIiwiaWF0IjoxNjk1MDU1MzgwLCJleHAiOjE2OTUwNTgzODB9.NoE_0NCb8AbFomf9soklqpyGd6lt7Q1lQZRXkjVfFXc

###
#GET List All User - Testing (No Need Authorization)
GET {{url_user}}users

##############################################################################################

###--- Category
#Post Create a Category
POST {{url_category}}create
{{json_category}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MDYzYmZmNzczNjVkOGJmYzA4MTk5MyIsIm5hbWUiOiJFZHdhcmQiLCJpZGVudGl0eSI6IkFkbWluIiwiaWF0IjoxNjk1MDU1MzgwLCJleHAiOjE2OTUwNTgzODB9.NoE_0NCb8AbFomf9soklqpyGd6lt7Q1lQZRXkjVfFXc

{
    "name":"JavaScript",
    "parent":"65069fac698e7a712e72dc9b"
}

###
#GET ALL Categorical List by User
GET {{url_category}}categoricalList
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MDYzYmZmNzczNjVkOGJmYzA4MTk5MyIsIm5hbWUiOiJFZHdhcmQiLCJpZGVudGl0eSI6IkFkbWluIiwiaWF0IjoxNjk1MDU1MzgwLCJleHAiOjE2OTUwNTgzODB9.NoE_0NCb8AbFomf9soklqpyGd6lt7Q1lQZRXkjVfFXc

###
#PUT Update one of Categories
PUT {{url_category}}65069624d281709fa7340802
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MDYzYmZmNzczNjVkOGJmYzA4MTk5MyIsIm5hbWUiOiJFZHdhcmQiLCJpZGVudGl0eSI6IkFkbWluIiwiaWF0IjoxNjk0OTgzNDg1LCJleHAiOjE2OTQ5ODY0ODV9.uXDq73yg0OCin7m8hxLz8AuozBBoUHjhZYjIMU7eDk4
{{json_category}}

{
    "name": "Traveling"
}

###
#DELETE Delete one of Categories
DELETE {{url_category}}65069ade868c6f3b5909d670
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MDYzYmZmNzczNjVkOGJmYzA4MTk5MyIsIm5hbWUiOiJFZHdhcmQiLCJpZGVudGl0eSI6IkFkbWluIiwiaWF0IjoxNjk0OTgzNDg1LCJleHAiOjE2OTQ5ODY0ODV9.uXDq73yg0OCin7m8hxLz8AuozBBoUHjhZYjIMU7eDk4


###
#GET List All Categories - Testing (No Need Authorization)
GET {{url_category}}categories

##############################################################################################

###--- Article

###
#POST Create a Article
POST {{url_article}}create
{{json_article}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MDYzYmZmNzczNjVkOGJmYzA4MTk5MyIsIm5hbWUiOiJFZHdhcmQiLCJpZGVudGl0eSI6IkFkbWluIiwiaWF0IjoxNjk0OTgzNDg1LCJleHAiOjE2OTQ5ODY0ODV9.uXDq73yg0OCin7m8hxLz8AuozBBoUHjhZYjIMU7eDk4

{
    "userId": "65063bd777365d8bfc08198f",
    "coverPic": "jkljlkjkldjklwjdlwkjdlk",
    "title":"Large Language Model in Out Society",
    "categories": "65069fac698e7a712e72dc9b",
    "body": "Hi, I would like to talke about OPEN AI",
    "status": "3"
}

###
#GET All Article List by User
GET {{url_article}}articleList
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MDYzYmZmNzczNjVkOGJmYzA4MTk5MyIsIm5hbWUiOiJFZHdhcmQiLCJpZGVudGl0eSI6IkFkbWluIiwiaWF0IjoxNjk0OTgzNDg1LCJleHAiOjE2OTQ5ODY0ODV9.uXDq73yg0OCin7m8hxLz8AuozBBoUHjhZYjIMU7eDk4


###
#PUT Update One of Articles
PUT {{url_article}}65076674b79f63f3f78babb8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MDYzYmZmNzczNjVkOGJmYzA4MTk5MyIsIm5hbWUiOiJFZHdhcmQiLCJpZGVudGl0eSI6IkFkbWluIiwiaWF0IjoxNjk0OTgzNDg1LCJleHAiOjE2OTQ5ODY0ODV9.uXDq73yg0OCin7m8hxLz8AuozBBoUHjhZYjIMU7eDk4
{{json_article}}

{
    "body":"LLM model is useful in translating programming language."
}

###
#DELETE Delete one of Tasks
DELETE {{url_article}}65076674b79f63f3f78babb8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MDYzYmZmNzczNjVkOGJmYzA4MTk5MyIsIm5hbWUiOiJFZHdhcmQiLCJpZGVudGl0eSI6IkFkbWluIiwiaWF0IjoxNjk0OTgzNDg1LCJleHAiOjE2OTQ5ODY0ODV9.uXDq73yg0OCin7m8hxLz8AuozBBoUHjhZYjIMU7eDk4

###
#GET List All Articles - Testing (No Need Authorization)
GET {{url_article}}articles